### PR TITLE
Fix logs and console for Ruby 3.3

### LINKED ISSUE #833: LogWriter not compatible with the Ruby 3.3 implementation of Logger
The current implementation of the `Bridgetown::LogWriter` class is incompatible with the Ruby 3.3 implementation of `Logger`.

It seems that `Bridgetown::LogWriter` chooses not to call the `super` initializer of the `Logger` class, but the implementation in Ruby 3.3 adds a new instance variable `@level_override` in https://github.com/ruby/ruby/commit/194520f80e1cdb71faa055d731450855a1ddb8d1. This causes the `Bridgetown::LogWriter` to have problems when requesting the current log level using `level`, as this now uses the `@level_override` instance variable which is not defined in `Bridgetown::LogWriter`.

**Bridgetown Version**: 1.3.1

**To Reproduce**
Start or test any Bridgetown project with a log format that extends from `Bridgetown::LogWriter`, e.g. `Bridgetown::Rack::Logger`.

**Current behavior**
It fails with an exception since `@level_override` is not initialized:
```
% bridgetown test
bridgetown aborted!
NoMethodError: undefined method `[]' for nil (NoMethodError)

    @level_override[Fiber.current] || @level
                   ^^^^^^^^^^^^^^^
/Users/remco/.rvm/gems/ruby-3.3.0/gems/bridgetown-core-1.3.1/lib/bridgetown-core/log_adapter.rb:45:in `adjust_verbosity'
/Users/remco/.rvm/gems/ruby-3.3.0/gems/bridgetown-core-1.3.1/lib/bridgetown-core/configuration.rb:244:in `config_files'
/Users/remco/.rvm/gems/ruby-3.3.0/gems/bridgetown-core-1.3.1/lib/bridgetown-core.rb:162:in `configuration'
/Users/remco/.rvm/gems/ruby-3.3.0/gems/bridgetown-core-1.3.1/lib/bridgetown-core.rb:274:in `load_tasks'
```

**Expected behavior**
A log line should be written ;)

**Screenshots**
N/A

**Computing environment (please complete the following information):**
 - OS: any
 - Browser any
 - Browser Version any
 - Ruby Version >= 3.3

**Additional context**
None

### PR DESCRIPTION
**Pull request by jaredcwhite**
Resolves #833

### CODE REVIEW

**Comment by jaredcwhite** [comment]
Ran into a problem trying to get CI to work with Ruby 3.3 — seems there's no prebuilt extension available for Nokolexbor yet.

File: bridgetown-core/lib/bridgetown-core/log_writer.rb [hunk 1]
```diff
@@ -2,18 +2,12 @@
...
-    def initialize # rubocop:disable Lint/MissingSuper
-      @progname = nil
-      @level = DEBUG
-      @default_formatter = Formatter.new
-      @logdev = $stdout
-      @formatter = proc do |_, _, _, msg|
-        msg.to_s
-      end
+    def initialize
+      super $stdout, formatter: proc { |_, _, _, msg| msg.to_s }
```
Comment (davidstosik) [inline bridgetown-core/lib/bridgetown-core/log_writer.rb:6]: 💯
